include: package:flutter_lints/flutter.yaml

linter:

  rules:
    prefer_const_constructors: true
    avoid_print: true
    always_specify_types: true
    unnecessary_this: true
    use_key_in_widget_constructors: true